channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - tensorflow-intel==2.16.1
  - tensorflow==2.16.1
name: mlflow-env
